`Homepage`: https://bgolearn.netlify.app/

The training data are stored in `./data/train.xlsx`, and the search-space data are stored in `./data/visual_samples.xlsx`.

The dataset includes four input features, namely Sn, Bi, In, and Ti, together with one target variable, T.

The objective is to determine the combination of Sn, Bi, In, and Ti that maximizes T.

In [1]:
# import training data
import pandas as pd
data = pd.read_excel('./data/train.xlsx')
print(data)

      Sn   Bi   In   Ti       T
0   92.9  3.0  2.5  0.1   64.60
1   92.7  3.0  2.5  0.3   62.59
2   92.5  3.0  2.5  0.5   72.05
3   91.9  3.0  3.5  0.1   66.60
4   91.7  3.0  3.5  0.3   70.29
5   91.5  3.0  3.5  0.5   68.33
6   91.9  4.0  2.5  0.1   77.65
7   91.7  4.0  2.5  0.3   80.49
8   91.5  4.0  2.5  0.5   81.03
9   90.9  4.0  3.5  0.1   78.59
10  90.7  4.0  3.5  0.3   84.98
11  90.5  4.0  3.5  0.5   87.58
12  90.9  5.0  2.5  0.1   87.42
13  90.7  5.0  2.5  0.3   94.48
14  90.5  5.0  2.5  0.5   95.07
15  89.9  5.0  3.5  0.1   92.51
16  89.7  5.0  3.5  0.3   89.85
17  89.5  5.0  3.5  0.5   90.41
18  86.8  5.5  5.5  0.7  106.65
19  86.9  5.5  5.4  0.7  110.56
20  86.9  5.5  5.5  0.6  113.44
21  92.5  2.5  3.4  0.1   65.51
22  92.6  2.5  3.3  0.1   62.67
23  92.4  2.5  3.4  0.2   65.40
24  92.4  1.5  4.5  0.1   74.64
25  92.2  1.5  4.7  0.1   78.49
26  92.4  1.5  4.4  0.2   73.94


In [2]:
# import search space data
import pandas as pd
vs = pd.read_excel('./data/visual_samples.xlsx')
print(vs)

         Sn   Bi   In   Ti
0      95.4  1.5  1.5  0.1
1      95.3  1.5  1.5  0.2
2      95.2  1.5  1.5  0.3
3      95.1  1.5  1.5  0.4
4      95.0  1.5  1.5  0.5
...     ...  ...  ...  ...
11762  87.2  5.5  5.5  0.3
11763  87.1  5.5  5.5  0.4
11764  87.0  5.5  5.5  0.5
11765  86.9  5.5  5.5  0.6
11766  86.8  5.5  5.5  0.7

[11767 rows x 4 columns]


In [3]:
import Bgolearn.BGOsampling as BGOS
Bgolearn = BGOS.Bgolearn() 

Mymodel = Bgolearn.fit(data_matrix = data.iloc[:,:-1], Measured_response = data.iloc[:,-1], virtual_samples = vs,)
Mymodel.EI()

 ____                 _                           
| __ )   __ _   ___  | |  ___   __ _  _ __  _ __  
|  _ \  / _` | / _ \ | | / _ \ / _` || '__|| '_ \ 
| |_) || (_| || (_) || ||  __/| (_| || |   | | | |
|____/  \__, | \___/ |_| \___| \__,_||_|   |_| |_|
        |___/                                     

Author : Bin Cao
Affiliation : Hong Kong University of Science and Technology (Guangzhou)
URL : https://bgolearn.netlify.app/
How to cite: 
Cao B et al., Bgolearn: A Unified Bayesian Optimization Framework for Accelerating Materials Discovery.
arXiv:2601.06820 (2026). https://doi.org/10.48550/arXiv.2601.06820
Executed on : 2026-04-07 14:50:44  | Have a great day.
The internal model is instantiated with optimized homogenous noise
The baseline is calculated based on the training dataset.
current optimal is : 62.59
The next datum recomended by Expected Improvement : 
 x =  [95.3  1.5  1.5  0.2]
The predictions of Bgolearn are : 
 y =  62.16954630574878


(array([4.10898579e+00, 4.24502811e+00, 4.17842064e+00, ...,
        8.74815138e-11, 3.58986245e-13, 1.97317116e-12]),
 array([[95.3,  1.5,  1.5,  0.2]]))

In [4]:
import Bgolearn.BGOsampling as BGOS
Bgolearn = BGOS.Bgolearn() 

Mymodel = Bgolearn.fit(data_matrix = data.iloc[:,:-1], Measured_response = data.iloc[:,-1], virtual_samples = vs)
Mymodel.EI_log()

 ____                 _                           
| __ )   __ _   ___  | |  ___   __ _  _ __  _ __  
|  _ \  / _` | / _ \ | | / _ \ / _` || '__|| '_ \ 
| |_) || (_| || (_) || ||  __/| (_| || |   | | | |
|____/  \__, | \___/ |_| \___| \__,_||_|   |_| |_|
        |___/                                     

Author : Bin Cao
Affiliation : Hong Kong University of Science and Technology (Guangzhou)
URL : https://bgolearn.netlify.app/
How to cite: 
Cao B et al., Bgolearn: A Unified Bayesian Optimization Framework for Accelerating Materials Discovery.
arXiv:2601.06820 (2026). https://doi.org/10.48550/arXiv.2601.06820
Executed on : 2026-04-07 14:50:45  | Have a great day.
The internal model is instantiated with optimized homogenous noise
The baseline is calculated based on the training dataset.
current optimal is : 62.59
The next datum recomended by Expected Improvement : 
 x =  [95.3  1.5  1.5  0.2]
The predictions of Bgolearn are : 
 y =  62.16954630574878


(array([  1.41317866,   1.4457508 ,   1.42993573, ..., -11.51291672,
        -11.51292543, -11.51292527]),
 array([[95.3,  1.5,  1.5,  0.2]]))

In [5]:
import Bgolearn.BGOsampling as BGOS
Bgolearn = BGOS.Bgolearn() 
Mymodel = Bgolearn.fit(data_matrix = data.iloc[:,:-1], Measured_response = data.iloc[:,-1], virtual_samples = vs)
Mymodel.UCB()

 ____                 _                           
| __ )   __ _   ___  | |  ___   __ _  _ __  _ __  
|  _ \  / _` | / _ \ | | / _ \ / _` || '__|| '_ \ 
| |_) || (_| || (_) || ||  __/| (_| || |   | | | |
|____/  \__, | \___/ |_| \___| \__,_||_|   |_| |_|
        |___/                                     

Author : Bin Cao
Affiliation : Hong Kong University of Science and Technology (Guangzhou)
URL : https://bgolearn.netlify.app/
How to cite: 
Cao B et al., Bgolearn: A Unified Bayesian Optimization Framework for Accelerating Materials Discovery.
arXiv:2601.06820 (2026). https://doi.org/10.48550/arXiv.2601.06820
Executed on : 2026-04-07 14:50:45  | Have a great day.
The internal model is instantiated with optimized homogenous noise
The next datum recomended by Upper confidence bound  : 
 x =  [95.3  1.5  1.5  0.2]
The predictions of Bgolearn are : 
 y =  62.16954630574878


(array([52.27219138, 52.06454533, 52.19652913, ..., 98.60729558,
        99.91386383, 99.65831671]),
 array([[95.3,  1.5,  1.5,  0.2]]))

In [6]:
pip show Bgolearn


Name: Bgolearn
Version: 3.0.0
Summary: A Bayesian global optimization package for material design
Home-page: https://github.com/Bin-Cao/Bgolearn
Author: CaoBin
Author-email: bcao686@connect.hkust-gz.edu.cn
License: MIT License
Location: /Users/jacob/miniconda3/lib/python3.9/site-packages
Requires: art, matplotlib, multiprocess, numpy, pandas, scikit-learn, scipy
Required-by: 
Note: you may need to restart the kernel to use updated packages.


In [9]:
import numpy as np
import pandas as pd
import Bgolearn.BGOsampling as BGOS

# ---------- Test objective (maximisation) ----------
def f_true(X):
    # X: shape (N, 2)
    x1 = X[:, 0]
    x2 = X[:, 1]
    return np.sin(5 * np.pi * x1) * np.cos(5 * np.pi * x2) + \
           0.5 * np.cos(10 * np.pi * x1) * np.sin(10 * np.pi * x2)

# ---------- Initialisation ----------
n_init = 5
X = np.random.rand(n_init, 2)
y = f_true(X)

# Convert to DataFrame (Bgolearn style)
data = pd.DataFrame(np.hstack([X, y.reshape(-1, 1)]))

# ---------- Virtual sampling space ----------
grid_size = 100
x1 = np.linspace(0, 1, grid_size)
x2 = np.linspace(0, 1, grid_size)
X1, X2 = np.meshgrid(x1, x2)
vs = np.vstack([X1.ravel(), X2.ravel()]).T   # (N_grid, 2)

# ---------- BGO object ----------
Bgolearn = BGOS.Bgolearn()

# ---------- BO loop ----------
for t in range(20):

    # ----- Fit surrogate model -----
    model = Bgolearn.fit(
        data_matrix=data.iloc[:, :-1],
        Measured_response=data.iloc[:, -1],
        virtual_samples=vs
    )

    # ----- Acquisition (Expected Improvement) -----
    _, x_next = model.EI()   # directly use Bgolearn's recommended point
    x_next = np.array(x_next).reshape(1, -1)

    # ----- Evaluate true function -----
    y_next = f_true(x_next).item()

    # ----- Update dataset -----
    new_row = np.hstack([x_next.flatten(), y_next])
    data.loc[len(data)] = new_row

    # ----- Logging -----
    best_y = data.iloc[:, -1].max()
    print(f"Iter {t+1}: selected x = [{x_next[0,0]:.4f}, {x_next[0,1]:.4f}], "
          f"y = {y_next:.4f}, best so far = {best_y:.4f}")

# ---------- Final recommendation ----------
best_idx = data.iloc[:, -1].idxmax()
x_best = data.iloc[best_idx, :-1].values
y_best = data.iloc[best_idx, -1]

print(f"\nBest found: x = [{x_best[0]:.4f}, {x_best[1]:.4f}], y = {y_best:.4f}")


 ____                 _                           
| __ )   __ _   ___  | |  ___   __ _  _ __  _ __  
|  _ \  / _` | / _ \ | | / _ \ / _` || '__|| '_ \ 
| |_) || (_| || (_) || ||  __/| (_| || |   | | | |
|____/  \__, | \___/ |_| \___| \__,_||_|   |_| |_|
        |___/                                     

Author : Bin Cao
Affiliation : Hong Kong University of Science and Technology (Guangzhou)
URL : https://bgolearn.netlify.app/
How to cite: 
Cao B et al., Bgolearn: A Unified Bayesian Optimization Framework for Accelerating Materials Discovery.
arXiv:2601.06820 (2026). https://doi.org/10.48550/arXiv.2601.06820
Executed on : 2026-04-07 14:53:08  | Have a great day.
The internal model is instantiated with optimized homogenous noise
The baseline is calculated based on the training dataset.
current optimal is : -0.16362688064537503
The next datum recomended by Expected Improvement : 
 x =  [0.81818182 0.71717172]
The predictions of Bgolearn are : 
 y =  0.10209411107744344
Iter 1: selected